# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: FortifyScanCentralSAST@7
  inputs:
    scanCentralCtrlUrl: 'http://azscc.japaneast.cloudapp.azure.com:8080/scancentral-ctrl'
    scanCentralClientToken: 'OWJkNTk0MmYtODYyZS00OWUzLWFjMmYtZTlkMTk0ODI3NTNj'
    sscUrl: 'https://azssc.japaneast.cloudapp.azure.com/ssc'
    sscCiToken: 'YjE4ZjMxOGQtNDI0Ni00MDQwLWE0ZTQtNjI1Yzk1NzkzZGUw'
    uploadToSSC: true
    applicationName: 'hackigniter'
    applicationVersion: '1.0'
